### ISSUE TITLE
not getting a predictable number of trends 

### ISSUE THREAD

**Issue by buddypepper** [AdamMoses-GitHub/MMM-TwitterTrendsByPlace#2]
For some reason, all day today I've only been getting 4 trends. My max is set for 15, though normally it only returns 10. My phone gives me 20, so I'm not sure what the trouble is.

**Comment by AdamMoses-GitHub** [comment]
This is an expected behavior, as fetching from the API and what the app shows you does not function in the same way, I'm sure Twitter does this for their own reasons.

If you look at the config option for "numberOfTrendsToShow" I did try and cover that: "The number of trending topics to list. If set to 0 it will show all the trending topics for the place that have any tweet volume information available. Do note that the number of trending topics provided by Twitter is not fixed and can be many or just a few."
